### ISSUE TITLE
Not showing paginator

### ISSUE THREAD

**Issue by davidromani** [Kreyu/data-table-bundle#114]
I've only seeing the paginator template when there is no page query parameter selected in the URL

<img width="1002" alt="Captura de pantalla 2024-07-23 a les 13 39 53" src="https://github.com/user-attachments/assets/84d146a0-5150-4a41-a107-e808f5d48e05">

<img width="1006" alt="Captura de pantalla 2024-07-23 a les 13 40 08" src="https://github.com/user-attachments/assets/f629228e-f942-4e91-8b81-7d7a1acf3067">

I've seen a in base template this conditional:

```html
{% block kreyu_data_table %}
    {% set stimulus_controllers = ['kreyu--data-table-bundle--persistence'] %}

    {% if has_batch_actions %}
        {% set stimulus_controllers = stimulus_controllers|merge(['kreyu--data-table-bundle--batch']) %}
    {% endif %}

    <turbo-frame id="kreyu_data_table_{{ name }}" data-controller="{{ stimulus_controllers|join(' ') }}" target="_top">
        {{ block('action_bar') }}
        {{ block('table') }}

        {% if pagination_enabled %}
            {{ data_table_pagination(pagination) }}
        {% endif %}
    </turbo-frame>
{% endblock %}
```

How is this `pagination_enabled` variable determined?

**Comment by Kreyu** [comment]
Hey @davidromani!

By default, the `pagination_enabled` variable comes from the [data table option of the same same](https://data-table-bundle.swroblewski.pl/reference/types/data-table.html#pagination-enabled). It allows switching on/off the whole pagination feature, and I don't think it's causing the issue, unless you are modifying this option in some way.

The `data_table_pagination` function renders the `kreyu_data_table_pagination` block, that contains another condition:

```twig
{% block kreyu_data_table_pagination %}
    {% if page_count > 1 %}
        {{ block('pagination_widget', theme) }}
    {% endif %}
{% endblock %}
```

The `page_count` comes from the `PaginationView` object of the `DataTableView`:

https://github.com/Kreyu/data-table-bundle/blob/main/src/Pagination/PaginationView.php#L23

...which is based on the value returned by the `Pagination` class:

https://github.com/Kreyu/data-table-bundle/blob/main/src/Pagination/Pagination.php#L45-L52

The pagination class is just a simple helper, created from the result set returned by your proxy query:

https://github.com/Kreyu/data-table-bundle/blob/main/src/DataTable.php#L623-L628

What I've noticed on the screenshots you provided is this:

![image](https://github.com/user-attachments/assets/2f279d61-1410-48a4-8c56-eb3b0a99a69b)

By default, it shows a range of first and last item of the currently displayed page. The 1 - 1 suggests there's only a single item on the currently displayed page. For me, it looks like you're using a custom proxy query similar to the one you described in #108:

```php
// in the discussion, you provided a BatchAnalysisArrayProxyQuery
// its getResult() method returns a ResultSet with currentPageItemCount statically set to "1":
return new ResultSet(
    iterator: new \ArrayIterator(iterator_to_array($resultArrayDtos)),
    currentPageItemCount: 1, // <-- here
    totalItemCount: count($resultArrayDtos),
);
```

Please let me know if there's custom logic similar above in your case - maybe that's the cause. 

Cheers!

**Comment by Kreyu** [comment]
I've noticed code snippet in your comment in #63:

```php
public function getResult(): ResultSetInterface
{
    return new ResultSet(
        iterator: new \ArrayIterator(iterator_to_array($this->data)),
        currentPageItemCount: $this->page,
        totalItemCount: count($this->data),
    );
}
```

The `currentPageItemCount` should return item count of current displayed page (instead of a current page). I suspect this single line is causing the issue here.

**Comment by davidromani** [comment]
Thanks for you answer @Kreyu.

For now, my custom ArrayProxyQuery is returning 7 elements and I'm trying to fix the pagination problem forcing to a 3 items per page setting. Show `setDefaultPaginationData` method call in my `BatchAnalysisDataTableType`:

```php
<?php

namespace App\Datatable\Type;

use App\Datatable\Query\ArrayProxyQuery;
use App\Doctrine\Enum\SortOrderEnum;
use Kreyu\Bundle\DataTableBundle\Filter\FilterData;
use Kreyu\Bundle\DataTableBundle\Filter\FilterInterface;
use Kreyu\Bundle\DataTableBundle\Filter\Operator;
use Kreyu\Bundle\DataTableBundle\Filter\Type\CallbackFilterType;
use Kreyu\Bundle\DataTableBundle\Bridge\PhpSpreadsheet\Exporter\Type\CsvExporterType;
use Kreyu\Bundle\DataTableBundle\Bridge\PhpSpreadsheet\Exporter\Type\XlsxExporterType;
use Kreyu\Bundle\DataTableBundle\Column\Type\NumberColumnType;
use Kreyu\Bundle\DataTableBundle\Column\Type\TextColumnType;
use Kreyu\Bundle\DataTableBundle\Pagination\PaginationData;
use Kreyu\Bundle\DataTableBundle\Sorting\SortingData;
use Kreyu\Bundle\DataTableBundle\Type\AbstractDataTableType;
use Kreyu\Bundle\DataTableBundle\DataTableBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BatchAnalysisDataTableType extends AbstractDataTableType
{
    public function buildDataTable(DataTableBuilderInterface $builder, array $options): void
    {
        $builder
            ->addColumn(
                'batchCode',
                TextColumnType::class,
                [
                    'label' => 'batchCode',
                    'property_path' => '[batchCode]',
                    'sort' => true,
                    'export' => true,
                ]
            )
            ->addColumn(
                'totalWorkstationSeconds',
                NumberColumnType::class,
                [
                    'label' => 'totalWorkstationSeconds',
                    'property_path' => '[totalWorkstationSeconds]',
                    'sort' => true,
                    'export' => true,
                ]
            )
            ->addFilter(
                'batchCode',
                CallbackFilterType::class,
                [
                    'default_operator' => Operator::Equals,
                    'callback' => function (ArrayProxyQuery $query, FilterData $data, FilterInterface $filter): void {
                        $query->filterDataBy($data, $filter);
                    },
                ]
            )
            ->addFilter(
                'totalWorkstationSeconds',
                CallbackFilterType::class,
                [
                    'default_operator' => Operator::Equals,
                    'callback' => function (ArrayProxyQuery $query, FilterData $data, FilterInterface $filter): void {
                        $query->filterDataBy($data, $filter);
                    },
                ]
            )
            ->addExporter('csv', CsvExporterType::class)
            ->addExporter('xlsx', XlsxExporterType::class)
            ->setDefaultSortingData(SortingData::fromArray([
                'batchCode' => strtolower(SortOrderEnum::ASC->value),
            ]))
            ->setDefaultPaginationData(new PaginationData(
                page: 1,
                perPage: 3,
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'filtration_enabled' => true,
        ]);
    }
}
```


Is this ProxyQueryInterface implementation right?

```php
<?php

namespace App\Datatable\Query;

use App\Doctrine\Enum\SortOrderEnum;
use Kreyu\Bundle\DataTableBundle\Filter\Filter;
use Kreyu\Bundle\DataTableBundle\Filter\FilterData;
use Kreyu\Bundle\DataTableBundle\Pagination\PaginationData;
use Kreyu\Bundle\DataTableBundle\Query\ResultSet;
use Kreyu\Bundle\DataTableBundle\Sorting\SortingData;
use Kreyu\Bundle\DataTableBundle\Query\ProxyQueryInterface;
use Kreyu\Bundle\DataTableBundle\Query\ResultSetInterface;

final class ArrayProxyQuery implements ProxyQueryInterface
{
    public function __construct(
        private array $data,
        private readonly int $page = 1,
    ) {
    }

    public function sort(SortingData $sortingData): void
    {
        foreach ($sortingData->getColumns() as $column) {
            usort($this->data, function ($a, $b) use ($column) {
                if ($column->getDirection() === strtolower(SortOrderEnum::ASC->value)) {
                    return ($a[$column->getName()] < $b[$column->getName()]) ? -1 : 1;
                } else {
                    return ($a[$column->getName()] > $b[$column->getName()]) ? -1 : 1;
                }
            });
        }
    }

    public function paginate(PaginationData $paginationData): void
    {
        if ($this->page > 1) {
            $total = count($this->data);
            $limit = $paginationData->getPerPage();
            $totalPages = ceil($total / $limit);
            $page = max($this->page, 1);
            $page = min($page, $totalPages);
            $offset = ($page - 1) * $limit;
            if( $offset < 0 ) {
                $offset = 0;
            }
            $this->data = array_slice($this->data, $offset, $limit);
        }
    }

    public function getResult(): ResultSetInterface
    {
        return new ResultSet(
            iterator: new \ArrayIterator(iterator_to_array($this->data)),
            currentPageItemCount: 3,
            totalItemCount: count($this->data),
        );
    }

    public function filterDataBy(FilterData $filterData, Filter $filter): void
    {
        $this->data = array_filter($this->data, function ($item) use ($filterData, $filter) {
            return $item[$filter->getConfig()->getName()] === $filterData->getValue();
        });
    }
}
```

**Comment by davidromani** [comment]
But I don't understand why the base datatable list view URL (without pagination query parameter) is returing the full list of 7 records. And when I click over a pagination item, then the result set is showing the paginated items (3 per page) but the paginator view is dissappearing.

<img width="993" alt="Captura de pantalla 2024-07-24 a les 8 43 00" src="https://github.com/user-attachments/assets/b2998e69-14e7-456a-bd21-9b7101bd6f51">

**Comment by Kreyu** [comment]
> Is this ProxyQueryInterface implementation right?

Not yet. I'll explain in steps:

> But I don't understand why the base datatable list view URL /admin/production/batch/batch-analysis (without pagination query parameter) is returing the full list of 7 records.

Your `paginate()` method is slicing the data only if the page is greater than 1, therefore, the first page contains all the records (as it is then passed to result set in `getResult()` method).

> And when I click over a pagination item (/admin/production/batch/batch-analysis?page_batch_analysis=2), then the result set is showing the paginated items (3 per page list) but the paginator view at page bottom is dissappearing.

Your `getResult()` method is using `count($this->data);` as `totalItemCount`. On first page, this equal to 7, because of the reason explained above. On the second page, it will equal to 3, because the data array is sliced to 3 items. This is why the pagination controls are not showing, because for the bundle, it seems the collection has 3 items of 3 items total.

Save the count of the data array before slicing it (preferably in the constructor, as the data array can change over time, so you can't do this in `paginate()` method) to be able to pass it as `totalItemCount`. Then, use `count($this->data)` as `currentPageItemCount`, because the data array contains records of currently displayed page:

```php
final class ArrayProxyQuery implements ProxyQueryInterface
{
    public function __construct(
        private array $data,
        private readonly int $page = 1,
    ) {
        $this->totalItemCount = count($data);
    }
    
    public function paginate(PaginationData $paginationData): void
    {
        $total = count($this->data);
        $limit = $paginationData->getPerPage();
        $totalPages = ceil($total / $limit);
        $page = max($this->page, 1);
        $page = min($page, $totalPages);
        $offset = ($page - 1) * $limit;
        if( $offset < 0 ) {
            $offset = 0;
        }
        $this->data = array_slice($this->data, $offset, $limit);
    }
    
    public function getResult(): ResultSetInterface
    {
        return new ResultSet(
            iterator: new \ArrayIterator(iterator_to_array($this->data)),
            currentPageItemCount: count($this->data),
            totalItemCount: $this->totalItemCount,
        );
    }
}
```

This should fix the issue, _however_, I don't understand why we're manually handling pagination on the dataset fully fetched from the database - it seems like a waste of memory 😄 Isn't it possible to make your `WorkOrderResultRepository::batchAnalysis()` method handle the pagination on the database side?

**Comment by davidromani** [comment]
fully working! many thanks!!

**Comment by davidromani** [comment]
> This should fix the issue, _however_, I don't understand why we're manually handling pagination on the dataset fully fetched from the database - it seems like a waste of memory 😄 Isn't it possible to make your `WorkOrderResultRepository::batchAnalysis()` method handle the pagination on the database side?

Related with your comment, as far as I understand if I read [the documentation](https://data-table-bundle.swroblewski.pl/docs/features/extensibility.html#creating-custom-proxy-query), if I implement my own ProxyQueryInterface I must define how the pagination (and sort) is done in my `ArrayProxyQuery` class, not in the controller or repository level.

**Comment by Kreyu** [comment]
> Related with your comment, as far as I understand if I read [the documentation](https://data-table-bundle.swroblewski.pl/docs/features/extensibility.html#creating-custom-proxy-query), and if I implement my own ProxyQueryInterface I must define how the pagination (and sort) is done in my `ArrayProxyQuery` class, not in the controller or repository level.

Yes, but that doesn't mean that the custom proxy query class should retrieve a whole dataset - this makes the entire pagination process pretty useless, as all the records are already loaded into memory. By creating a custom proxy query you have to provide a way to interact with the data source to easily sort, paginate and apply filters.

This process can be entirely different based on the scenario. If you're using Doctrine ORM, you don't create a custom proxy query, as it is currently built into the bundle, and you can just pass an instance of QueryBuilder. If for example you're using raw SQL queries (via Doctrine DBAL), then probably the best way to integrate it with the bundle is to create `DoctrineDbalProxyQuery` that accepts an instance of DBAL `QueryBuilder` (as it is different than the ORM one), and apply pagination criteria to the query builder straight from the proxy query. More complex cases may require something completely different.

For me, proxy query integrating with arrays always seemed like something you probably don't want to use. The proxy query should integrate with **_data source_** (Doctrine ORM, DBAL, other ORMs, external API), not with _**data (data source result)**_ we want do display.

**Comment by davidromani** [comment]
> In your case, the `WorkOrderResultRepository::batchAnalysis()` should probably return a query builder, so the bundle can **interact** with it by applying sorting, pagination and filtration. Using result of a query kinda makes a lot of the bundle unusable, unless a ton of manual work is done (but in this case this bundle is pretty useless).

Well, if I try to apply a pure Doctrine approach, it seems impossible for me to achieve it. Maybe you can check where is the problem exactlly... I appreciate your time so much @Kreyu.

```php
// Controller action method
public function batchAnalysisAction(Request $request, WorkOrderResultRepository $wor): Response
{
    $dataTable = $this->createDataTable(BatchAnalysisDataTableType::class, $wor->batchAnalysisQB());
    $dataTable->handleRequest($request);
    if ($dataTable->isExporting()) {
        return $this->file($dataTable->export());
    }

    return $this->render('@App/admin/reports/batch_analysis.html.twig', [
        'batchAnalysisTable' => $dataTable->createView(),
    ]);
}
```

```php
// Repository
public function batchAnalysisQB(): QueryBuilder
{
    return $this->createQueryBuilder('wor')
        ->select('b.code AS batchCode, SUM(wor.workstationSeconds) AS totalWorkstationSeconds')
        ->join('wor.workOrder', 'wo')
        ->join('wo.batch', 'b')
        ->groupBy('b.code')
    ;
}
```

Then, I'm getting this error...

`[Semantical Error] line 0, col 209 near 'batchCode as': Error: Class App\Entity\Production\WorkOrderResult has no field or association named batchCode`

...because there is no columns/properties `batchCode` or `totalWorkstationSeconds` in my entity. This is the reason why I think that is better to apply a DTO approach but maybe I'm miss confused.

**Comment by Kreyu** [comment]
At first glance, the query builder looks fine. This is a case that can (and should) be handled without custom proxy query, so I am sure we can make it work!

> [Semantical Error] line 0, col 209 near 'batchCode as': Error: Class App\Entity\Production\WorkOrderResult has no field or association named batchCode

This worries me a bit, because of the "near" part: `batchCode as` - not sure where it comes from. Can you retrieve this query builder result manually without any problems?

```php
dd($wor->batchAnalysisQB()->getQuery()->getResult());
```

Does it return data properly in arrays (instead of entities)?

```php
[
    [
        'batchCode' => '...',
        'totalWorkstationSeconds' => '...',
    ], 
    [
        'batchCode' => '...',
        'totalWorkstationSeconds' => '...',
    ],
    ...
]
```

What I initially suspected, was invalid DQL paths for sorting, but the error would be different... 

I'm trying to recreate this issue in one of my projects, so the entities will be different, but the idea is the same:

```php
$queryBuilder = $productRepository->createQueryBuilder('product')
    ->select('product.id AS foo')
    ->addSelect('COUNT(commercialGroupSchedules.id) as bar')
    ->join('product.commercialGroupSchedules', 'commercialGroupSchedules')
    ->groupBy('product.id')
;

$dataTable = $this->createDataTableBuilder($queryBuilder)
    ->addColumn('foo', TextColumnType::class, [
        'property_path' => '[foo]',
        'sort' => 'foo',
    ])
    ->addColumn('bar', TextColumnType::class, [
        'property_path' => '[bar]',
        'sort' => 'bar',
    ])
    ->setDefaultSortingData(SortingData::fromArray(['foo' => 'desc']))
    ->getDataTable()
;
```

The QueryBuilder returns arrays instead of entities, e.g. `[['foo' => 1, 'bar' => 2], ['foo' => 3, 'bar' => 4]]`, and the data table works properly. I've noticed a bug that results in Doctrine exception if you provided multiple selects in a single `select()` method call. I will be creating a separate issue for that. This is probably not a cause of your issue, but to be sure, please break the select into two separate `select` and `addSelect` calls (temporarily, until I fix this use-case):

```php
public function batchAnalysisQB(): QueryBuilder
{
    return $this->createQueryBuilder('wor')
        ->select('b.code AS batchCode')
        ->addSelect('SUM(wor.workstationSeconds) AS totalWorkstationSeconds')
        ->join('wor.workOrder', 'wo')
        ->join('wo.batch', 'b')
        ->groupBy('b.code')
    ;
}
```

**Comment by Kreyu** [comment]
Also, you can try temporarily disabling the sorting behavior for the data table - just to make sure, comment out `sort` option of each column, and check whether the issue still exists.

**Comment by davidromani** [comment]
> Also, you can try temporarily disabling the sorting behavior for the data table - just to make sure, comment out `sort` option of each column, and check whether the issue still exists.

On disabled columns sorting it shows right the table, but raise up a pagination problem again 😱

<img width="788" alt="Captura de pantalla 2024-07-24 a les 15 24 14" src="https://github.com/user-attachments/assets/817d08f7-cd17-43c0-b189-159054489815">

**Comment by Kreyu** [comment]
> On disabled columns sorting it shows right the table

Okay, so, I suspect this issue is caused by an incorrect column configuration. I am assuming that your `BatchAnalysisDataTableType` definition is the same as the one you provided in https://github.com/Kreyu/data-table-bundle/issues/63#issuecomment-2244989098.

First, focus on splitting the DQL SELECT into two separate calls due to a bug explained in the #115 - your definition is _correct_, but I completely forgot you can do that, and it kinda breaks some of the internals 😅

```diff
public function batchAnalysisQB(): QueryBuilder
{
    return $this->createQueryBuilder('wor')
-       ->select('b.code AS batchCode, SUM(wor.workstationSeconds) AS totalWorkstationSeconds')
+       ->select('b.code AS batchCode')
+       ->addSelect('SUM(wor.workstationSeconds) AS totalWorkstationSeconds')
        ->join('wor.workOrder', 'wo')
        ->join('wo.batch', 'b')
        ->groupBy('b.code')
    ;
}
```

Then, focus on the definition of your columns. If you set `sort` option to `true`, the sort property path will equal to the value of `property_path` option if given, otherwise it will equal to the column name. So, because you have to set `property_path` to include square brackets, you also have to explicitly provide the `sort` path:

```diff
$builder
    ->addColumn(
        'batchCode',
        TextColumnType::class,
        [
            'label' => 'batchCode',
            'property_path' => '[batchCode]',
-           'sort' => true,
+           'sort' => 'batchCode',
            'export' => true,
        ]
    )
    ->addColumn(
        'totalWorkstationSeconds',
        NumberColumnType::class,
        [
            'label' => 'totalWorkstationSeconds',
            'property_path' => '[totalWorkstationSeconds]',
-           'sort' => true,
+           'sort' => 'totalWorkstationSeconds',
            'export' => true,
        ]
    )
```

I think this was giving an error, even if you haven't sorted by any column manually - because below you've provided a default sorting data with `batchCode` column. Other than that, because now you're using a built-in proxy query instead of a custom one, you can simplify the definition of filters by replacing `CallbackFilterType` with Doctrine-specific `StringFilterType`, etc.

Now, about those 4 198 total items... Currently I have no clue what's causing this, as I've never seen that before, and I've been handling this exact use case (queries that return arrays with some `COUNT`s or `SUM`s) multiple times across multiple projects. I would be really thankful if we could continue this topic further, because maybe its some weird edge case and can be considered as a bug.

What would be incredibly helpful is some sort of a small project that contain similar definition of those entities and the data table, but I understand this is a lot of work, but making it reproducible would be amazing. Other than that, you can check the Symfony Profiler to see what queries are performed, and maybe we'll see something alarming. I suspect there's an issue related with the Doctrine ORM Paginator (which the Doctrine ORM integration is using), because total item count comes from the Doctrine  paginator's `count` method. 

Thanks for the discussion though, we've already identified one bug in the bundle, that means a lot to me 👍🏻

**Comment by davidromani** [comment]
> Then, focus on the definition of your columns. If you set `sort` option to `true`, the sort property path will equal to the value of `property_path` option if given, otherwise it will equal to the column name. So, because you have to set `property_path` to include square brackets, you also have to explicitly provide the `sort` path

it works

**Comment by davidromani** [comment]
> Other than that, because now you're using a built-in proxy query instead of a custom one, you can simplify the definition of filters by replacing `CallbackFilterType` with Doctrine-specific `StringFilterType`

Truly, now I've replaced the `CallbackFilterType` but when I filter the batchCode column it shows this error:

```
Unknown result variable: batchCode
```

**Comment by davidromani** [comment]
> What would be incredibly helpful is some sort of a small project that contain similar definition of those entities and the data table

I'll try to provide it you during the following week. Thanks for your help!

**Comment by Kreyu** [comment]
> Sure, now I've replaced the `CallbackFilterType` by `StringFilterType` but when I filter the batchCode column it shows this error:
> 
> ```
> Unknown result variable: batchCode
> ```
> 
> I need to define something else inside the options array?
> 
> ```
> ->addFilter(
>     'batchCode',
>     StringFilterType::class,
>     [
>     ]
> )
> ```

Not sure where this error comes from (I don't really recognize it), but you'll need to provide a `query_path` - a DQL path to perform filtering on. That's because you cannot add WHERE clauses using SELECT aliases.

```php
->addFilter(
    'batchCode',
    StringFilterType::class,
    [
        'query_path' => 'b.code',
    ]
)
```

However, because your second column, `totalWorkstationSeconds` is using an aggregate function, we cannot add `WHERE` clause. Instead, we have to add a `HAVING` clause, but the built-in filters have no way to configure them to do that - somehow I missed that, I'll create a separate issue.

Temporarily, you can keep the `CallbackFilterType` like so:

```php
->addFilter('totalWorkstationSeconds', CallbackFilterType::class, [
    'callback' => function (DoctrineOrmProxyQuery $query, FilterData $data) {
        // note: using getUniqueParameterId is completely optional
        $parameterName = 'totalWorkstationSeconds'.$query->getUniqueParameterId();

        $query
            ->andHaving("SUM(wor.workstationSeconds) = :$parameterName")
            ->setParameter($parameterName, $data->getValue())
        ;
    },
])
```

> > What would be incredibly helpful is some sort of a small project that contain similar definition of those entities and the data table
>
> I'll try to provide it you during the following week. Thanks for your help!

Thank you so much 😄

**Comment by davidromani** [comment]
> Not sure where this error comes from (I don't really recognize it), but you'll need to provide a `query_path` - a DQL path to perform filtering on. That's because you cannot add WHERE clauses using SELECT aliases.

it works! 

> However, because your second column, `totalWorkstationSeconds` is using an aggregate function, we cannot add `WHERE` clause. Instead, we have to add a `HAVING` clause, but the built-in filters have no way to configure them to do that - somehow I missed that, I'll create a separate issue (edit - added #116).
> 
> Temporarily, you can keep the `CallbackFilterType` like so:
> 
> ```
> ->addFilter('totalWorkstationSeconds', CallbackFilterType::class, [
>     'callback' => function (DoctrineOrmProxyQuery $query, FilterData $data) {
>         // note: using getUniqueParameterId is completely optional
>         $parameterName = 'totalWorkstationSeconds'.$query->getUniqueParameterId();
> 
>         $query
>             ->andHaving("SUM(wor.workstationSeconds) = :$parameterName")
>             ->setParameter($parameterName, $data->getValue())
>         ;
>     },
> ])
> ```

doesn't throw any error, but it seems that there is a problem with data types...  because it doesn't match

<img width="801" alt="Captura de pantalla 2024-07-25 a les 13 26 56" src="https://github.com/user-attachments/assets/f2ef15d3-2736-471b-8a1b-082c5386284e">
<img width="907" alt="Captura de pantalla 2024-07-25 a les 13 27 09" src="https://github.com/user-attachments/assets/bc2f15a5-4bcb-4bfe-8fe2-d06baa031d55">

**Comment by Kreyu** [comment]
Hmm, hard to tell, but maybe it's because by default the filters are rendered as [`TextType`](https://symfony.com/doc/current/reference/forms/types/text.html) form type, therefore the given value is string, it doesn't parse it properly - you'd have to check the profiler to see why this query is incorrect.

If that's the case, you can either:
- set [`form_type`](https://data-table-bundle.swroblewski.pl/reference/types/filter/callback.html#form-type) option of this filter to [`NumberType`](https://symfony.com/doc/current/reference/forms/types/number.html) FQCN, 
- provide a third argument to the QB `->setParameter()` method to set the parameter type to `Doctrine\DBAL\ParameterType::INTEGER`
- just cast the `$data->getValue()` to integer
