### ISSUE TITLE
Render Raw HTML in Column Values

### ISSUE THREAD

**Issue by TheoD02** [Kreyu/data-table-bundle#45]
## Acknowledgment
Before I dive into the details of this issue, this vendor was a long-awaited addition to my toolkit, and it's truly awesome! 🌟  

Big thanks to you for your exceptional work ! 😄 

## Overview
This issue is a feature request to enhance the data rendering capabilities of our application by allowing the rendering of raw HTML in column values. The primary goal is to provide more flexibility when displaying data in tables, especially in cases where HTML tags within the data should be displayed as-is.

### Feature Description
- Proposed adding a new option called `render_raw` to the column settings in the data table builder.
- When `render_raw` is set to `true`, it should render the column value as raw HTML, preserving any HTML tags within the data.
- The option should be applied at the column level, allowing granular control over which columns should render HTML as-is.
- This feature can improve the user experience and data presentation in our application.

### Proposed Changes
- Add the `render_raw` option to the column configuration in the data table builder.
- Modify the `addColumn` method in `ColumnType.php` to include the `render_raw` attribute with a default value of `false`.
- Ensure the `render_raw` option is available for use in the application's documentation.
- Provide examples and usage guidelines for developers.

## Example Code
```php
private function buildDataTable(DataTableBuilderInterface $builder, array $options): void {
    $builder
        ->addColumn('id', NumberColumnType::class, [
            'sort' => true,
        ])
        ->addColumn('name', TextColumnType::class)
        ->addColumn('customers', TextColumnType::class, [
            'formatter' => function (PersistentCollection $supplier) {
                $url = $this->urlGenerator->generate('app_home',  ['id' => $supplier->getId()]);
                $urls = array_map(
                    fn(Customer $customer) => sprintf(
                        '<a href="%s">%s</a>',
                        $url,
                        $customer->getName(),
                    ),
                    $supplier->toArray()
                );
                return implode(', ', $urls);
            },
            'render_raw' => true,
        ]);
}
```
## Render
![image](https://github.com/Kreyu/data-table-bundle/assets/72203064/1ba01fdf-8da4-4738-972f-f1005873dbab)

If this issue is accepted and validated, I plan to open a pull request on the repository to implement the feature. Your feedback and thoughts on this enhancement would be highly appreciated. see [Preview PR](https://github.com/Kreyu/data-table-bundle/compare/main...TheoD02:data-table-bundle:feat/add_option_to_render_raw_html)

**Comment by Kreyu** [comment]
Hey @TheoD02, thank you so much for the kind words and your time!

While I understand the motive behind the option, first, let's see the currently supported ways of handling this:

- using the [TemplateColumnType](https://data-table-bundle.swroblewski.pl/reference/columns/types/template/), which accepts a path to the template and variables to pass to the template. This is useful for quick prototyping, or for custom columns that wouldn't really make use of custom column type - although those cases are rare and I'm suggesting to create the custom column type anyway;

- creating the custom column type, in example you provided, would be something like `CustomersCollectionColumnType`, which will handle this case specifically, and all the PHP logic will be stored in the type class, and presentation logic in the twig template. Then, HTML can be provided in the custom theme, in the Twig blocks:
  -  `column_customers_collection_header` - for header, optionally;
  -  `column_customers_collection_value` - for value, also optionally;

- using any column type, but providing a `block_prefix` option (for example: `customers_collection`), and providing the HTML in the custom theme like in the example above;

Now, some explanation why I think that should stay like it is:

- the presentation logic is stored in the twig, not in PHP code, which makes for easier maintenance and readability;

- formatter is not really a good place to return a HTML, because it makes the column value itself as a HTML, and this breaks some of the other column types. For example, think of `BooleanColumnType`, which returns a HTML in the formatter - this breaks the column, as the templates are checking whether the column value is "truthy", therefore it will always be `true`; 

And last but not least, for the example you provided, **I understand that this may be just a simple example**, but remember that this case can be handled by using [CollectionColumnType](https://data-table-bundle.swroblewski.pl/reference/columns/types/collection/), and setting its `entry_type` option to [LinkColumnType](https://data-table-bundle.swroblewski.pl/reference/columns/types/link/). If you need to provide something custom to the column, I would suggest creating a custom column type, setting the `CollectionColumnType` as parent, and setting the default `entry_type` to `LinkColumnType` in the `configureOptions()`.

I'm open for discussion though, maybe there are really some cases that would benefit from the "raw" option, but currently I think putting the presentation logic to Twig templates are more intuitive (and sooo much easier to manage).

**Comment by TheoD02** [comment]
Hi, 

Thanks for the quick reply, I didn't have time to reply earlier, sorry.

I think I was expecting that if `render_raw` is equal to `true` then `formatter` would automatically render as raw in twig. This was wrong.

The solution you mentioned in your reply seems easier to maintain and more suitable for extended use than formatter, I think this issue can be closed and can provide more explanation if needed for anyone looking for another way to render a field.
