### ISSUE TITLE
Email address as user ID breaks persistence

### ISSUE THREAD

**Issue by steveWinter** [Kreyu/data-table-bundle#46]
Our application uses email addresses as usernames which means I'm logged in as `steve@msdev.co.uk`. When attempting to enable persistence for personalisation the following error is given.

`Cache tag "kreyu_data_table_persistence_steve@msdev.co.uk" contains reserved characters "{}()/\@:".`

**Comment by Kreyu** [comment]
Hey! Woah, thanks for the input!

This case is covered and explained in [the documentation](https://data-table-bundle.swroblewski.pl/troubleshooting/#persistence-cache-tag-contains-reserved-characters-error), and I suggest changing the persistence subject identifier to something else, for example - entity IDs.

This error is caused by the **cache** itself - it cannot save keys with reserved characters. However:

- the persistence layer is using cache adapter by default, but can be changed by user to anything else - this means this error is only tied to the cache adapter itself;
- the persistence subject identifier can be changed from default (`UserInterface::getUserIdentifier()`) to provide something unique without reserved characters;
- stripping anything from the persistence identifier seems dangerous in some cases. For example, let's say one persistence subject has "foo@bar" identifier, the another one has "foo/bar", in the result, those two will be exactly the same, and they will be overwriting their persistence data;

Although, I understand why handling this automatically in the bundle should be a priority for better developer experience. What I suggest is, instead of stripping the characters, let's url encode them. Additionally, I'm not sure, whether to change this in the whole persistence system, or to target the cache specifically, and change it in the [CachePersistenceAdapter](https://github.com/Kreyu/data-table-bundle/blob/main/src/Persistence/CachePersistenceAdapter.php#L52).

**Comment by Kreyu** [comment]
Version 0.16 contains a fix to this issue - the cache keys are now url encoded, which prevents the usage of reserved characters, and prevents key overlapping.
